-- person.sql

CREATE TABLE PERSON(
	PID NUMBER PRIMARY KEY,
	PNAME NVARCHAR2(200) NOT NULL,
	PAGE NUMBER CHECK (PAGE > 0)
);

CREATE SEQUENCE SEQ_PERSON;

-- 프로시져 생성
CREATE OR REPLACE PROCEDURE CHANGENAME(
	P_PID IN NUMBER, P_PNAME IN OUT NVARCHAR2
)
IS
BEGIN
	
	UPDATE PERSON
	SET PNAME = P_PNAME
	WHERE PID = P_PID;
	
	SELECT PNAME
	INTO P_PNAME
	FROM PERSON
	WHERE PID = P_PID;
END;

-- 함수 생성
CREATE OR REPLACE FUNCTION GETNAME(P_PID IN NUMBER)
RETURN NVARCHAR2
IS
	V_PNAME PERSON.PNAME%TYPE;
BEGIN
	SELECT PNAME
	INTO V_PNAME
	FROM PERSON
	WHERE PID = P_PID;

	RETURN V_PNAME;
	
	EXCEPTION
		WHEN NO_DATA_FOUND THEN
			RETURN '해당 PID 없음!';
END;
